name: WWW_Next

on:
  push:
    branches: [ "master" ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: "root"
        password: ${{secrets.PASSWORD}}
        port: 22
        script: |
          cd /usr/local/nginx/html && rm -rf Web-www && pm2 stop www &&
          git clone https://github.com/Silvora/Web-www.git &&
          cd Web-www && yarn && pm2 start www
